name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Kinematicula.sln
    - name: Build
      run: dotnet build ./Kinematicula.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test ./Kinematicula.sln --verbosity normal
